version: "3.9"
services:
  server:
    build:  ./server
    ports: 
    - "5000:5000"
    volumes: 
    - ./server:/app
    environment: 
      FLASK_ENV: development
  web:
    build: ./ecomm-app
    ports: 
      - "3000:3000"
    volumes: 
      - ./ecomm-app:/user/src/app
    depends_on: 
      - server